name: "warp-docker-http-proxy-go-server"

networks:
  dpanel-network:
    external: true
    name: "dpanel-network"
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.31.123.0/24"
        - subnet: "fd12:5687:4425:5555::/64"

services:
  http-proxy-go-server:
    domainname: http-proxy-go-server
    privileged: true
    networks:
      - "dpanel-network"
    ports:
      - "58877:58877/tcp"

    command:
      - "sh"
      - "-c"
      - "-x"
      - "'./main'\
        \ '-dohurl' 'https://doh-server.masx200.ddns-ip.net' '-dohip' '104.21.14.41' '--dohalpn=h2'\
        \ '-port' '58877' '-username' 'admin' '-password' '${password}' '-dohalpn=h3'\
        \ '-dohurl' 'https://doh-server.masx200.ddns-ip.net' '--dohip=2606:4700:3031::ac43:9db6'   '-dohurl' 'https://one.one.one.one/dns-query' '-dohip' '1.0.0.1' '--dohalpn=h2'\
        \ '-dohurl' 'https://one.one.one.one/dns-query' '-dohip' '2606:4700:4700::1001' '--dohalpn=h2'\
        \ '-dohurl' 'https://one.one.one.one/dns-query' '-dohip' '1.0.0.1' '--dohalpn=h3'\
        \ '-dohurl' 'https://one.one.one.one/dns-query' '-dohip' '2606:4700:4700::1001' '--dohalpn=h3'  "

    container_name: "http-proxy-go-server"

    environment:
      - "GOLANG_VERSION=1.24.4"
      - "GOTOOLCHAIN=local"
      - "GOPATH=/go"
      - "TZ=Asia/Shanghai"
      - "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    image: "docker.cnb.cool/masx200/docker_mirror/http-proxy-go-server:2.6.0"

    ipc: "private"

    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

    restart: "always"

    stdin_open: true

    tty: true

    working_dir: "/app"

  warp-docker:
    depends_on:
      - "http-proxy-go-server"
    network_mode: "container:http-proxy-go-server"
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - "NET_ADMIN"

    container_name: "warp-docker"
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
      - "net.ipv4.conf.all.src_valid_mark=1"

    devices:
      - "/dev/net/tun:/dev/net/tun"

    entrypoint:
      ["bash", "-x", "/entrypoint.sh", "/status.sh"]

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    image: "docker.cnb.cool/masx200/docker_mirror/warp-docker:latest"
    ipc: "private"

    logging:
      driver: "json-file"
      options: {}

    privileged: true

    restart: "always"

    security_opt:
      - "label=disable"

    stdin_open: true

    tty: true


  curl-monitor:
    depends_on:
      - "http-proxy-go-server"
    privileged: true
    user: "0:0"
    image: curlimages/curl:latest
    container_name: curl-monitor
    networks:
      - dpanel-network
    command:
      - /bin/sh
      - -c
      - "while true; do curl -v -I https://www.google.com -x http://http-proxy-go-server:58877  --proxy-user admin:${password} --http2; sleep 60; done"
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "100m"
version: "3.6"
